apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: home-wildcard-certificate
  namespace: default
spec:
  secretName: home-wildcard-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: "*.home.maxanderson.tech"
  dnsNames:
    - "*.home.maxanderson.tech"
---
apiVersion: traefik.containo.us/v1alpha1
kind: TLSStore
metadata:
  name: default
  namespace: default
spec:
  defaultCertificate:
    secretName: home-wildcard-tls