apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: frontend
spec:
  jobLabel: app.kubernetes.io/part-of
  selector:
    matchLabels:
      app: frontend
  endpoints:
    - targetPort: 80
      path: /metrics
      interval: 5s
