apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pihole-etc-dnsmasq
  namespace: pihole
spec:
  storageClassName: "local-path-custom"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
