apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: pihole-secret
  namespace: pihole
spec:
  encryptedData:
    WEBPASSWORD: AgBZXNsI1hyiSJU9gmlb1SwefXNM+CHne+PsoFhsmcqCSoZp1IeSRrMf3aclpaYxsXTgNgg3JXWtFRpYn5xoXf85Zv25REmnEnufWCwITz1i5HBt2U5v3NseZh5GQmY30C/Ujl29g/DJ+etssYBTvfpma6yGL8fAkOOVZdtS1cSKj6CQwVXvX0abNbMOg9LhqKxIxMmI9weJzRccyPd6xSAVGL2FEgNGvz1X6p/NlTs09uG2ILIIEGOiQdEqNhtSqHfW40rA4NS5po7i7hol1R3tC/OwEPgdC29MdHleKr5TXnZ51uxlHmfJEgZIXzWFVoCgseZ+4RKYaBiz8xw8wuhQqvm//D1J+i+ZqNJkrpwSr+XcFxYkdIIB80pcLzIwcT1T+yWsifOphdoQ004879kONRzw+rQlDN7uTGrg4PcoBbWkMtEp//4xFLwP1F8mZSZd/zLf2fDL94TG54KgDodRzz2CgPpOtiqhLqzFXwSF49Jhd/RDGOEj2B33t/3ya5C8Pe/q02DSvAjJRdWMvp7exo9unRZJ8cb7iVsL8pfqUjdGciJjTUI33Vhl37/7QhdW+0e7R2zSntEWfRvqaGwfF1b4EO/cGjihPiW998kgtzd595BIsGk38cuulOqJiOTur47DisLSWwP0gWj1IZAoMza7MudM8ZQXI2Kd2S8eztXhbw6giFFcylk+bALNekNZlt9zjZQ5/EuKJdZyZKKcEQ==
  template:
    metadata:
      creationTimestamp: null
      name: pihole-secret
      namespace: pihole

