apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - pvc.yaml
  - deployment.yaml
  - service.yaml

configMapGenerator:
  - name: minecraft-creative-env-configmap
    envs:
      - "./config/settings.env"
