apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: pihole-password
  namespace: pihole
spec:
  encryptedData:
    WEBPASSWORD: AgClzZYWooSPPzqH6GzwkQh1ZhiNwHigIgYfyjtyjjmH+1pQIY40BvILqOeLpZ/yHBzc0cNRKhYZ/3HItFtuv/qEmNLw2hztX+Lx4fEXFvm9SvpRbqJ/Qmmr1iXe2dYQs1hSSYYUvgyH0O4l6X3XxS8BBm6h9mUlUMvcZDsoCiVOeUMhGc0kyWiqWVDh8BnDtvYwAYW7Cahjh3+dICxr6rK0Qw46GB1TREoU2r10qLryLFP8Mcfu5yCId8TdiBRKxJNHDm2i/ZgrqQtb17ROhQ+l/Zq7ZGK05/7BDp/oUlrR4LYDJECoWmnIZqlpPJyeNMtxECK40BqqFHDSiaqvbZbWocW+//BcF7O6f0qqUhm8W6Rdnb+N0AyfkYofpMqGFeT8OD4Rqo3paAZwv82mHz3vYf6ZNiCoKT+tNBTlHA7RLjdg1MDpcGFtr+UGrMnG9To99v6bY6WEL5QzBeieAhUaTTra3vksAWCteLntWEsphLrGh0pO0RV3sSoQ1p+IRT1IptXq3Y5aj9y6A7wuDAXgB6tpbJlfMDBy1XgYbtuvDi8bmpmkI9+JVsf6vY8nhc7TpRwH+wSRT/GTjRTJA73rhEmlV75uleHOZS3tp4cRY8G6Uvie6UEv6re4Rd7GOq+tjwuk7bOjrom/cf5Lk1BjmgXoG8CnFXa0Y+6WG64MiGyI6DFzPM4p07a0hu7Tq8qLJBiGOzsn2Mbzunz7HgaS0w==
  template:
    metadata:
      creationTimestamp: null
      name: pihole-password
      namespace: pihole
    type: Opaque

