[[servers]]
name = "atl-fw"
ip = "192.168.1.30"

[[servers]]
name = "atl-tor-a"
ip = "10.100.1.2"

[[servers]]
name = "atl-tor-b"
ip = "10.100.1.3"

[[servers]]
name = "nyc-fw"
ip = "192.168.1.40"

[[servers]]
name = "nyc-tor-a"
ip = "10.200.1.2"

[[servers]]
name = "nyc-tor-b"
ip = "10.200.1.3"