apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: traefik
  namespace: kube-system
spec:
  valuesContent: |-
    deployment:
      podAnnotations:
        linkerd.io/inject: ingress
    service: 
      spec:
        externalTrafficPolicy: Local
