apiVersion: v1
kind: Service
metadata:
  name: netbootxyz-service
spec:
  type: LoadBalancer
  selector:
    app: netbootxyz
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      name: web
    - protocol: UDP
      port: 69
      targetPort: 69
      name: tftp
    - protocol: TCP
      port: 8080
      targetPort: 80
      name: assets
