# ---
# apiVersion: cert-manager.io/v1
# kind: Certificate
# metadata:
#   name: argocd-tls
#   namespace: argocd
# spec:
#   secretName: argocd-tls
#   issuerRef:
#     name: letsencrypt-prod
#     kind: ClusterIssuer
#   commonName: argocd.home.maxanderson.tech
#   dnsNames:
#     - argocd.home.maxanderson.tech
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: redirecthttps
  namespace: argocd
spec:
  redirectScheme:
    scheme: https
    permanent: true
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: argocd-server-https
  namespace: argocd
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`argocd.home.maxanderson.tech`)
      priority: 10
      services:
        - name: argocd-server
          port: 80
    - kind: Rule
      match: Host(`argocd.home.maxanderson.tech`) && Headers(`Content-Type`, `application/grpc`)
      priority: 11
      services:
        - name: argocd-server
          port: 80
          scheme: h2c
  tls:
    secretName: argocd-tls
  #tls: {} # Don't specify TLS and allow Traefik to select the default TLS store
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: argocd-server-http
  namespace: argocd
spec:
  entryPoints:
    - web
  routes:
    - kind: Rule
      match: Host(`argocd.home.maxanderson.tech`)
      priority: 10
      middlewares:
        - name: redirecthttps
          namespace: argocd
      services:
        - name: argocd-server
          port: 80
