apiVersion: v1
kind: ConfigMap
metadata:
  name: netbox-configmap
data:
  TZ: America/New_York
  SUPERUSER_EMAIL: max.a.anderson95@gmail.com
  DB_NAME: netbox
  REDIS_HOST: netbox-redis
  REDIS_PORT: "6379"
