apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: netbox-db-cluster
spec:
  instances: 1
  primaryUpdateStrategy: unsupervised
  storage:
    size: 1Gi
  bootstrap:
    initdb:
      database: netbox
      owner: netbox_user
