apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: unifi-config-pvc
  namespace: unifi
spec:
  storageClassName: "local-path-custom"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
