apiVersion: v1
kind: Service
metadata:
  name: mc-router
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.1.16
  ports:
    - targetPort: web
      name: web
      port: 8080
    - targetPort: proxy
      name: proxy
      port: 25565
  selector:
    run: mc-router
