apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minecraft-legacy1-data-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: longhorn
