apiVersion: monitoring.coreos.com/v1alpha1
kind: ScrapeConfig
metadata:
  name: co2-monitor
  namespace: monitoring
  labels:
    release: kube-prometheus-stack
spec:
  staticConfigs:
    - labels:
        job: co2-monitor
      targets:
        - 192.168.1.2:8080
