# This is the application of applications that will deploy all other applications in the cluster
# This is the only application that should be manually deployed
# All other applications should be deployed by this application

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-app-of-apps
  namespace: argocd
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: default
  source:
    path: home-k8s-cluster/workloads/argo-manifests
    repoURL: https://github.com/MaxAnderson95/homelab.git
    targetRevision: v0.0.1
    directory:
      recurse: true
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
