apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: rancher-certificate
  namespace: cattle-system
spec:
  commonName: 'rancher.home.maxanderson.tech'
  dnsNames:
  - 'rancher.home.maxanderson.tech'
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-prod
  secretName: rancher-tls