apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: subtract
  labels:
    release: kube-prometheus-stack
spec:
  jobLabel: app.kubernetes.io/part-of
  namespaceSelector:
    matchNames:
      - calculator
  selector:
    matchLabels:
      component: subtract
  endpoints:
    - targetPort: 80
      path: /metrics
      interval: 5s
