apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kured
  namespace: argocd
spec:
  project: default
  source:
    chart: kured
    repoURL: https://kubereboot.github.io/charts
    targetRevision: 5.3.1 # App version 1.14.1
    helm:
      releaseName: kured
  destination:
    server: "https://kubernetes.default.svc"
    namespace: kured
