---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: pihole-secret
  namespace: external-dns
spec:
  encryptedData:
    EXTERNAL_DNS_PIHOLE_PASSWORD: AgBYizalFHXKuri0J4/MFJsXkH4avLrzFRVQ8cokZY/uMjZ0FBp3SHCd4B6g8k8Tlh3QBtFP6x+fslFIt4b7Bg1ZOyEeAo9zT/TI8VCvtv0MvLuKWuJqZOoPhw0DmfXIDGhvr3klU/KMhMuL4sJkV2e74nXK7sQ1xetm5/eTH6OQQ45ahMxtNbI8NGGEuQJ9OTpGxyAOIPBa2ysqHI4mGA2+XXmwDz1J0Szv2mtdgLt3xIRTnAHV4e3NFfdilgHhRWr583n77uAxJ9/Abi4fxjtczMLy9xxKjKskdZfQjlqpAHMAhMnO0qJSKqT35rFNlLxUkTQuqHKmkb9j3RR08c04mNLd+GUVzI6hTQc4UpA5bIluam6uKJtu5lukLwJWbYrFRKk/w4b3WFpi5P5Ld2VBI9i9DLW4xQ1dzQlXruIaj7hDGkUrLDWUtBFZhqJB8QuIVZMc1k5rP8iNNaXL9MUFad88wvMFlbt60Am4ZsGkhW18tlP2GrY9FJRx11LNIX5lIimgZWHrPAUjm9WWF5vDGOhX01a9fpoYO1bW3BVBPcvs0t2EoTDbKw2SQAZOrXhAqATSWN2nQ+IjS2vC3gsuqA0vy/0HX3Iq1MSnNNZUyLlCkR2Yz+VRPn2rcUvdTY9mNiYRIjtwxuJxLYo/xABREt0ZEWdgiZd1XrfNmZ4lIpAPShyFI6Nk/jWhXpYdNCbhI6oG3R7IHM+vtyKm3sKF9g==
  template:
    metadata:
      name: pihole-secret
      namespace: external-dns
