---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: pihole-secret
  namespace: kube-system
spec:
  encryptedData:
    EXTERNAL_DNS_PIHOLE_PASSWORD: AgCKy5KnyJHVAeO3pbGshP4akwV/RKbZeoplDVI7b5F8FCjErkDwfNokkYQEpnaQp4ZhUA3ksUxncFH1pfCtLBtovEw+3vvXxz2FmR3CpHnHrRrZIhMbrebE8O6vDi4ODSz1FVkUDnKBvCYg+rIIrZm2ABDcivpTBnIewnvuKnkX8oWwYpFvrO3CkU/mcfuWj+RW7gfukNJbFDIwY3mc9YOY1u3sWOEtWffqgEOkP5VUuOOniX1YNt0WrLAD3pGg1DnDuOYzLaAMgoDHVgLLDwGatQ06n85NRyRGpZ3qfK31o8gefUonN0274kI8rb3k9FgZXW9wN11cz5TLOBnWE4y5c9Z8do5kv/WS3asbceRZDTHspDj034mUAaLkHutoHmYa1qJhP6bbjxt5JAMg7d+2Qx6MZ4Nhllrb76dEOwwvQsuJYXVrXXKEUH2mc5+oCCiNvOui0L0t4Y2sz3v3Mgm1/xXYif3K+eRIS3spciBDcF5mCJpivAC9EoDiPBI0lr9DgS+qusJ9q1EWLjrHsD9gbnzgPaGGXMd8JBDNHViOAyHmd3M5l9QqJxSHH+vtugpwTebWeuHWCq00xzcH8R0vPzZW7u2AH3BiiuJ1dq7zml9wsB8ydIooZ4MnUPGXnWeH223voE4t4os8yR8XhYJeWXFsz742ynfXT0tY1bIUhc0FJBfNQF/cd1RJSGCTdEv88Nfzqc7DQtXpBQZd/Qk=
  template:
    metadata:
      name: pihole-secret
      namespace: kube-system
