apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: digitalocean-token
  namespace: dyndns
spec:
  encryptedData:
    token: AgB82t6nvj8dwHo5fp6XsLOPTzxLinNKhW0wx+YWXyoqQyP/wBDr1oarAw69F2T33ahThOvm/Qflcw+xvXah3X5oAzgfoYtfFpITqra95xqwl5SV521/RMOeHgllQa77OwiG7FGNV+1u4TB6mDdUx9vFf83ufP7hORSFs+F5CPNUgTywJoMSZswC4Yt9fVyoKtLYS8bu67m2+LCAf2XQ2qiO2b3Pm+Ttz+K3vSauJ9k9B1STBfxjSMSxGroUDtkd8zbGKgyS1OUJbdccBAE9tfiySaoECyYnZ1Fok8EGiilWu6AFbxxnFovtTh6WhyRFoogO4V6U8hU+HdZS7pCDujKnwRH1GT+Rh18dAM4GRdo1utwPzlcD40LZYPuW4tKayOP7DVkwH/JHGNSNI6WKe4DHzGS4KJjwopAVtfJyg0IrFTuFHBXs0pHg6QkPlOQStOsByRZdpFgF2oW6zE7a+7NAeCR1GXZdoWaqsilogA3FeOQaXaEHCaJ/cXex1KP4mX5n6D4HBryvXTGiUQ4xhkXNA8KLXyWNCNzA642N8Dtx7LcUWzcnvORtSxrPEt9RCrH6LtxnQYgIS89paUk7dtjfHfnNjiUUA8zWqMJimpduBdAzn00A7yisR/DDDMloPqGbKlCmQ2tWZSpsDrhyz6R9MIluuC771NuK9O+AHEaSXZyQbo00pkgnRTYtclumYIpCSeInFkJ1srlxoZ4qFm8jETJnqC77kEm+EOOIW0+qH5lHd9JS48ws+tAzrAge6IAEE9ZTKvvqIPM6/lzjLMU89THkFrg3zA==
  template:
    metadata:
      creationTimestamp: null
      name: digitalocean-token
      namespace: dyndns
    type: Opaque
