apiVersion: batch/v1
kind: CronJob
metadata:
  name: dyndns-home-maxanderson-tech
  namespace: dyndns
spec:
  schedule: "0 * * * *"
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 5
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: dyndns-updater
            image: maxanderson95/digitalocean-dyndns-updater:v1.1
            imagePullPolicy: IfNotPresent
            env:
              - name: DIGITALOCEAN_TOKEN
                valueFrom:
                  secretKeyRef:
                    name: digitalocean-token
                    key: token
              - name: RECORD_NAME
                value: "home"
              - name: ZONE_NAME
                value: "maxanderson.tech"
          restartPolicy: OnFailure

