apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
spec:
  project: default
  sources:
    - chart: cert-manager
      repoURL: https://charts.jetstack.io
      targetRevision: 1.13.2
      helm:
        releaseName: cert-manager
        valuesObject:
          installCRDs: true
          repliaCount: 1
          extraArgs:
            - --dns01-recursive-nameservers=8.8.8.8:53,8.8.4.4:53
            - --dns01-recursive-nameservers-only
          podDnsPolicy: "None"
          podDnsConfig:
            nameservers:
              - "8.8.8.8"
              - "8.8.4.4"
    - path: home-k8s-cluster/workloads/k8s-prod/cluster-issuer
      repoURL: https://github.com/MaxAnderson95/homelab.git
      targetRevision: HEAD
  destination:
    server: "https://kubernetes.default.svc"
    namespace: cert-manager
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
