apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: co2-monitor
  namespace: argocd
spec:
  destination:
    namespace: monitoring
    server: https://kubernetes.default.svc
  project: default
  source:
    path: home-k8s-cluster/workloads/k8s-prod/manifests/custom-monitoring
    repoURL: https://github.com/MaxAnderson95/homelab.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
