apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://github.com/MaxAnderson95/homelab.git
      path: home-k8s-cluster/workloads/k8s-prod/manifests/kube-prometheus/kube-prometheus-stack
      targetRevision: HEAD
      directory:
        jsonnet:
          libs:
            - home-k8s-cluster/workloads/k8s-prod/manifests/kube-prometheus/kube-prometheus-stack/vendor
        exclude: "**/*.json"
        recurse: true
    - repoURL: https://github.com/MaxAnderson95/homelab.git
      path: home-k8s-cluster/workloads/k8s-prod/manifests/kube-prometheus
      targetRevision: HEAD
  destination:
    server: "https://kubernetes.default.svc"
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
