apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus
  namespace: argocd
spec:
  project: default
  sources:
    - chart: kube-prometheus-stack
      repoURL: https://prometheus-community.github.io/helm-charts
      targetRevision: 55.5.0
      helm:
        releaseName: kube-prometheus-stack
        valuesObject:
          prometheus:
            prometheusSpec:
              enableAdminAPI: true
          prometheus-node-exporter:
            prometheus:
              monitor:
                relabelings:
                  - sourceLabels: [__meta_kubernetes_pod_node_name]
                    action: replace
                    targetLabel: instance
    - repoURL: https://github.com/MaxAnderson95/homelab.git
      path: home-k8s-cluster/workloads/k8s-prod/manifests/kube-prometheus
      targetRevision: HEAD
  destination:
    server: "https://kubernetes.default.svc"
    namespace: monitoring
  syncPolicy:
    # automated:
    #   prune: true
    #   selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
