apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sealed-secrets
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-1" # This is to ensure that the sealed-secrets controller is deployed before cert-manager which needs a secret unsealed to connect to DNS provider
spec:
  project: default
  source:
    chart: sealed-secrets
    repoURL: https://bitnami-labs.github.io/sealed-secrets
    targetRevision: 2.13.3 # App version 0.24.4
    helm:
      releaseName: sealed-secrets
      valuesObject:
        fullnameOverride: "sealed-secrets-controller" #This is to set the service (and other object names) to use the default that the CLI client expects
        namespace: "kube-system"
        secretName: "sealed-secrets-key" # I used an existing encryption key from an old cluster. Leave this configuration option out for the controller to generate an encryption key on first startup
  destination:
    server: "https://kubernetes.default.svc"
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
